name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      - name: Helm tool installer
        uses: Azure/setup-helm@v3
      - name: Lint
        run: |
          helm lint ./helm-charts/vaultwarden/
      - name: Package
        run: |
          helm package --version 0.1.${{ github.run_number }} ./helm-charts/vaultwarden/
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: chart
          path: vaultwarden-*.tgz
